name: chickies_ui
description: Dart package which defines chikies ui components.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: ^3.19.2
dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0


dev_dependencies:
  build_runner: ^2.4.8
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/